---
- hosts: raspberrypi3
  become: true
  roles:
  - basic4ubuntu

- hosts: azuresles12
  become: true
  roles:
  - basic4sles

- hosts: linux1rhel
  user: linux1
  become: true
  roles:
  - basic4rhel
